#if !defined(AFX_CALENDAR_H__250844EE_119F_4A32_9C68_C05DF63A2AF9__INCLUDED_)
#define AFX_CALENDAR_H__250844EE_119F_4A32_9C68_C05DF63A2AF9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCalendar wrapper class

class CCalendar : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCalendar)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7a65b153, 0xc0a, 0x433e, { 0x8b, 0xed, 0xa, 0x1e, 0xfd, 0x9f, 0xf, 0xed } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetMonth();
	void SetMonth(short);
	short GetYear();
	void SetYear(short);
	CString GetMonthYearFont();
	void SetMonthYearFont(LPCTSTR);
	CString GetDayFont();
	void SetDayFont(LPCTSTR);
	unsigned long GetDayColor();
	void SetDayColor(unsigned long);
	unsigned long GetMonthYearBackColor();
	void SetMonthYearBackColor(unsigned long);
	unsigned long GetDayTextColor();
	void SetDayTextColor(unsigned long);
	CString GetDayTextFont();
	void SetDayTextFont(LPCTSTR);
	unsigned long GetDayCaptionBackColor();
	void SetDayCaptionBackColor(unsigned long);
	CString GetDayCaptionFont();
	void SetDayCaptionFont(LPCTSTR);
	unsigned long GetDayCaptionForeColor();
	void SetDayCaptionForeColor(unsigned long);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	BOOL GetShowYear();
	void SetShowYear(BOOL);
	BOOL GetShowMonth();
	void SetShowMonth(BOOL);
	CString GetLicenseKey();
	void SetLicenseKey(LPCTSTR);
	unsigned long GetMonthYearForeColor();
	void SetMonthYearForeColor(unsigned long);
	short GetDayTextFontSize();
	void SetDayTextFontSize(short);
	short GetDay();
	void SetDay(short);

// Operations
public:
	BOOL SetHighLightDay(short iYear, short iMonth, short iDay, unsigned long clrHighLight);
	BOOL SetDayCaptions(short iIndex, LPCTSTR strCaption);
	BOOL SetMonthCaptions(short iIndex, LPCTSTR strCaption);
	void SetText(short iDay, LPCTSTR strText);
	CString GetText(short iYear, short iMonth, short iDay);
	unsigned long GetHighLightDay(short iYear, short iMonth, short iDay);
	short GetHighLightDayCount();
	CString FindHighLightDay(short iIndex);
	unsigned long FindHighLightDayColor(short iIndex);
	short GetTextCount();
	CString FindTextDay(short iIndex);
	CString FindText(short iIndex);
	void Redraw();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CALENDAR_H__250844EE_119F_4A32_9C68_C05DF63A2AF9__INCLUDED_)
